# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("governance", "0001_initial"),
        ("imports", "0001_initial"),
        ("institutions", "0001_initial"),
        ("offerings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_number", models.CharField(blank=True, max_length=80)),
                ("display_name", models.CharField(blank=True, max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_profiles",
                        to="institutions.institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("cohort_code", models.CharField(blank=True, max_length=80)),
                ("transition_events", models.JSONField(blank=True, default=list)),
                (
                    "admission_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="offerings.academicterm",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="curriculum.curriculumplan",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="institutions.program",
                    ),
                ),
                (
                    "revision_basis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_enrollments",
                        to="student_records.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ENROLLED", "Enrolled"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("VALIDATED", "Validated"),
                            ("HOMOLOGATED", "Homologated"),
                            ("TRANSFERRED", "Transferred"),
                            ("ANNULLED", "Annulled"),
                        ],
                        default="PLANNED",
                        max_length=24,
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("credits_earned", models.PositiveSmallIntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("SIA", "Sia"),
                            ("MANUAL", "Manual"),
                            ("IMPORT", "Import"),
                            ("RECOGNITION", "Recognition"),
                        ],
                        default="IMPORT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_attempts",
                        to="curriculum.courseversion",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_attempts",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_attempts",
                        to="offerings.academicterm",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_attempts",
                        to="student_records.programenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment", "status"], name="attempt_enrollment_status_idx"
                    ),
                    models.Index(
                        fields=["course_version", "status"], name="attempt_course_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment", "course_version", "attempt_number"),
                        name="attempt_enrollment_course_number_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_number__gte", 1)),
                        name="attempt_number_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("credits_earned__gte", 0)),
                        name="attempt_credits_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcademicRecognition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recognition_type",
                    models.CharField(
                        choices=[
                            ("EQUIVALENCE", "Equivalence"),
                            ("HOMOLOGATION", "Homologation"),
                            ("TRANSFER", "Transfer"),
                            ("SUBSTITUTION", "Substitution"),
                        ],
                        max_length=24,
                    ),
                ),
                ("credits_applied", models.PositiveSmallIntegerField(default=0)),
                ("resolution_reference", models.CharField(blank=True, max_length=240)),
                ("notes", models.TextField(blank=True)),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True, related_name="academic_recognitions", to="governance.evidence"
                    ),
                ),
                (
                    "source_course_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_recognitions",
                        to="curriculum.courseversion",
                    ),
                ),
                (
                    "target_course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_recognitions",
                        to="curriculum.courseversion",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recognitions",
                        to="student_records.programenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment", "recognition_type"],
                        name="recognition_enrollment_type_idx",
                    ),
                    models.Index(
                        fields=["target_course_version"], name="recognition_target_course_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcademicException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exception_type", models.CharField(max_length=80)),
                ("scope", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("rationale", models.TextField()),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True, related_name="academic_exceptions", to="governance.evidence"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_academic_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="academic_exceptions",
                        to="student_records.programenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment", "status"], name="exception_enrollment_status_idx"
                    ),
                    models.Index(fields=["valid_from", "valid_to"], name="exception_validity_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__isnull", True),
                            ("valid_from__isnull", True),
                            ("valid_to__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="exception_valid_range",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["institution", "student_number"], name="student_inst_number_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student_number", ""), _negated=True),
                fields=("institution", "student_number"),
                name="student_institution_number_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="programenrollment",
            index=models.Index(fields=["student", "status"], name="enrollment_student_status_idx"),
        ),
        migrations.AddIndex(
            model_name="programenrollment",
            index=models.Index(fields=["program", "status"], name="enrollment_program_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="programenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "program", "admission_term"),
                name="enrollment_student_program_term_unique",
            ),
        ),
    ]
