# Generated by Django 6.0.8 on 2026-08-16 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_records", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="academicexception",
            new_name="exception_enroll_status_idx",
            old_name="exception_enrollment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="academicrecognition",
            new_name="recognition_enroll_type_idx",
            old_name="recognition_enrollment_type_idx",
        ),
    ]
