# Generated by Django 6.0.8 on 2026-08-19 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student_records", "0005_cross_scope_invariants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="display_name",
            new_name="legacy_display_name",
        ),
    ]
