# Generated by Django 6.0.8 on 2026-08-19 04:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0007_curriculumassignmentpolicy_and_more"),
        ("student_records", "0007_backfill_person_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumAssignmentDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESOLVED", "Resolved"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("AUTOMATIC", "Automatic"), ("ADMIN_OVERRIDE", "Admin Override")],
                        max_length=24,
                    ),
                ),
                ("resolver_version", models.CharField(max_length=32)),
                ("input_data", models.JSONField()),
                ("reason_codes", models.JSONField(default=list)),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("decision_hash", models.CharField(max_length=64)),
                ("override_reason_code", models.CharField(blank=True, max_length=120)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_assignment_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_decisions",
                        to="student_records.programenrollment",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_decisions",
                        to="curriculum.curriculumassignmentpolicy",
                    ),
                ),
                (
                    "selected_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_decisions",
                        to="curriculum.curriculumplan",
                    ),
                ),
                (
                    "selected_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_decisions",
                        to="curriculum.curriculumrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["enrollment", "created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "-created_at"], name="assignment_decision_enroll_idx"
                    ),
                    models.Index(fields=["decision_hash"], name="assignment_decision_hash_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "RESOLVED"), _negated=True),
                            models.Q(
                                ("policy__isnull", False),
                                ("selected_plan__isnull", False),
                                ("selected_revision__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="assignment_resolved_has_policy_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("method", "AUTOMATIC"), _negated=True),
                            ("status", "RESOLVED"),
                            _connector="OR",
                        ),
                        name="assignment_automatic_is_resolved",
                    ),
                ],
            },
        ),
    ]
