# Generated by Django 6.0.8 on 2026-08-19 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0009_curriculumassignmentpolicyevidence_sealed_excerpt_hash_and_more"),
        ("institutions", "0001_initial"),
        ("offerings", "0004_split_scope_triggers"),
        ("student_records", "0009_assignment_decision_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="curriculumassignmentdecision",
            name="method",
            field=models.CharField(
                choices=[
                    ("AUTOMATIC", "Automatic"),
                    ("POLICY_EVALUATION", "Policy Evaluation"),
                    ("ADMIN_OVERRIDE", "Admin Override"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_enrollments",
                to="curriculum.curriculumplan",
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="revision_basis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_enrollments",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("selected_plan__isnull", True), ("selected_revision__isnull", True)),
                    models.Q(
                        ("selected_plan__isnull", False), ("selected_revision__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="assignment_selected_target_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="programenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("plan__isnull", True), ("revision_basis__isnull", True)),
                    models.Q(("plan__isnull", False), ("revision_basis__isnull", False)),
                    _connector="OR",
                ),
                name="enrollment_plan_revision_both_or_neither",
            ),
        ),
        migrations.AddConstraint(
            model_name="programenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "NEEDS_REVIEW"),
                    models.Q(("plan__isnull", False), ("revision_basis__isnull", False)),
                    _connector="OR",
                ),
                name="enrollment_resolved_status_has_curriculum",
            ),
        ),
    ]
