# Generated by Django 6.0.8 on 2026-08-19 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0010_assignment_policy_publication_guard"),
        ("student_records", "0011_pending_enrollment_scope_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="curriculumassignmentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("method", "ADMIN_OVERRIDE"), _negated=True),
                    models.Q(
                        ("decided_by__isnull", False),
                        models.Q(("override_reason_code", ""), _negated=True),
                        ("selected_plan__isnull", False),
                        ("selected_revision__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="assignment_override_has_actor_reason_target",
            ),
        ),
    ]
