# Generated by Django 6.0.8 on 2026-08-19 05:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_student_onboarding(apps: object, schema_editor: object) -> None:
    del schema_editor
    enrollment_model = apps.get_model("student_records", "ProgramEnrollment")  # type: ignore[attr-defined]
    onboarding_model = apps.get_model("student_records", "StudentOnboarding")  # type: ignore[attr-defined]
    existing = set(onboarding_model.objects.values_list("enrollment_id", flat=True))
    onboarding_model.objects.bulk_create(
        onboarding_model(enrollment_id=enrollment_id)
        for enrollment_id in enrollment_model.objects.exclude(id__in=existing).values_list(
            "id", flat=True
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0012_curriculumassignmentpolicy_allow_retired_revision"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("offerings", "0004_split_scope_triggers"),
        (
            "student_records",
            "0012_curriculumassignmentdecision_assignment_override_has_actor_reason_target",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "history_step_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IMPORTED", "Imported"),
                            ("SKIPPED", "Skipped for now"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("planning_load_target", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "tour_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="curriculumassignmentdecision",
            name="assignment_resolved_has_policy_target",
        ),
        migrations.AddField(
            model_name="curriculumassignmentdecision",
            name="override_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curriculum_assignment_override_decisions",
                to="governance.evidence",
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="review_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "RESOLVED"), _negated=True),
                    models.Q(
                        ("selected_plan__isnull", False),
                        ("selected_revision__isnull", False),
                        models.Q(
                            ("policy__isnull", False),
                            models.Q(
                                ("method", "ADMIN_OVERRIDE"), ("override_evidence__isnull", False)
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="assignment_resolved_has_policy_target",
            ),
        ),
        migrations.AddField(
            model_name="studentonboarding",
            name="current_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_onboarding_selections",
                to="offerings.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="studentonboarding",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="onboarding",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentonboarding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planning_load_target__isnull", True),
                    models.Q(("planning_load_target__gte", 1), ("planning_load_target__lte", 30)),
                    _connector="OR",
                ),
                name="onboarding_planning_load_target_range",
            ),
        ),
        migrations.RunPython(backfill_student_onboarding, migrations.RunPython.noop),
    ]
