# Generated by Django 6.0.8 on 2026-08-19 05:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0013_assignment_policy_guard_v2"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("student_records", "0015_enrollment_review_status_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumAssignmentOverrideAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason_code", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("revision_content_hash", models.CharField(blank=True, max_length=128)),
                ("revision_source_set_hash", models.CharField(blank=True, max_length=128)),
                ("sealed_snapshot_id", models.UUIDField(blank=True, null=True)),
                ("sealed_snapshot_sha256", models.CharField(blank=True, max_length=64)),
                ("sealed_storage_key_hash", models.CharField(blank=True, max_length=64)),
                ("sealed_excerpt_hash", models.CharField(blank=True, max_length=128)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="curriculumassignmentdecision",
            name="assignment_override_has_actor_reason_target",
        ),
        migrations.RemoveConstraint(
            model_name="curriculumassignmentdecision",
            name="assignment_resolved_has_policy_target",
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_assignment_override_authorizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_override_authorizations",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_override_authorizations",
                to="governance.evidence",
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_override_authorizations",
                to="curriculum.curriculumplan",
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="prepared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prepared_assignment_override_authorizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="revision_basis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_override_authorizations",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddField(
            model_name="curriculumassignmentdecision",
            name="override_authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_decisions",
                to="student_records.curriculumassignmentoverrideauthorization",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "RESOLVED"), _negated=True),
                    models.Q(
                        ("selected_plan__isnull", False),
                        ("selected_revision__isnull", False),
                        models.Q(
                            ("policy__isnull", False),
                            models.Q(
                                ("method", "ADMIN_OVERRIDE"),
                                ("override_evidence__isnull", False),
                                ("override_authorization__isnull", False),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="assignment_resolved_has_policy_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("method", "ADMIN_OVERRIDE"), _negated=True),
                    models.Q(
                        ("decided_by__isnull", False),
                        models.Q(("override_reason_code", ""), _negated=True),
                        ("override_evidence__isnull", False),
                        ("override_authorization__isnull", False),
                        ("selected_plan__isnull", False),
                        ("selected_revision__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="assignment_override_has_actor_reason_target",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumassignmentoverrideauthorization",
            index=models.Index(
                fields=["enrollment", "status"], name="asg_ovr_auth_enroll_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentoverrideauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "APPROVED"), _negated=True),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("approved_at__isnull", False),
                        models.Q(("content_hash", ""), _negated=True),
                        models.Q(("revision_content_hash", ""), _negated=True),
                        models.Q(("revision_source_set_hash", ""), _negated=True),
                        ("sealed_snapshot_id__isnull", False),
                        models.Q(("sealed_snapshot_sha256", ""), _negated=True),
                        models.Q(("sealed_storage_key_hash", ""), _negated=True),
                        models.Q(("sealed_excerpt_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="assignment_override_approved_is_sealed",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentoverrideauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_by__isnull", True),
                    models.Q(("approved_by", models.F("prepared_by")), _negated=True),
                    _connector="OR",
                ),
                name="assignment_override_separates_approval",
            ),
        ),
    ]
