# Generated by Django 6.0.8 on 2026-08-19 05:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DROP_LEGACY_GUARD_SQL = """
DROP TRIGGER IF EXISTS assignment_override_authorization_guard
ON student_records_curriculumassignmentoverrideauthorization;
DROP FUNCTION IF EXISTS protect_assignment_override_authorization();
"""

RESTORE_LEGACY_GUARD_SQL = """
CREATE OR REPLACE FUNCTION protect_assignment_override_authorization()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE approval_capability text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status = 'APPROVED' THEN
            RAISE EXCEPTION 'Approved assignment override authorizations cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF NEW.status = 'APPROVED'
       AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM 'APPROVED') THEN
        approval_capability := current_setting('app.assignment_override_approval', true);
        IF approval_capability IS DISTINCT FROM 'allowed'
           OR NEW.approved_by_id IS NULL OR NEW.approved_by_id = NEW.prepared_by_id
           OR NEW.approved_at IS NULL OR NEW.content_hash = ''
           OR NEW.revision_content_hash = '' OR NEW.revision_source_set_hash = ''
           OR NEW.sealed_snapshot_id IS NULL OR NEW.sealed_snapshot_sha256 = ''
           OR NEW.sealed_storage_key_hash = '' OR NEW.sealed_excerpt_hash = '' THEN
            RAISE EXCEPTION 'Override authorization approval requires the governed service';
        END IF;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status = 'APPROVED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Approved assignment override authorizations are immutable';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER assignment_override_authorization_guard
BEFORE INSERT OR UPDATE OR DELETE
ON student_records_curriculumassignmentoverrideauthorization
FOR EACH ROW EXECUTE FUNCTION protect_assignment_override_authorization();
"""

V2_GUARD_SQL = """
CREATE OR REPLACE FUNCTION protect_assignment_override_authorization()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE approval_capability text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status = 'APPROVED' THEN
            RAISE EXCEPTION 'Approved assignment override authorizations cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF NEW.status = 'APPROVED'
       AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM 'APPROVED') THEN
        approval_capability := current_setting('app.assignment_override_approval', true);
        IF approval_capability IS DISTINCT FROM 'allowed'
           OR NEW.seal_version <> 'OVERRIDE_AUTH_V2'
           OR NEW.approved_by_id IS NULL OR NEW.approved_by_id = NEW.prepared_by_id
           OR NEW.approved_at IS NULL OR NEW.content_hash = ''
           OR NEW.revision_content_hash = '' OR NEW.revision_source_set_hash = ''
           OR NEW.revision_status = '' OR NEW.sealed_snapshot_id IS NULL
           OR NEW.sealed_snapshot_sha256 = '' OR NEW.sealed_storage_key_hash = ''
           OR NEW.sealed_excerpt_hash = '' OR NEW.sealed_locator_hash = ''
           OR NEW.sealed_locator = '' OR NEW.sealed_source_title = '' THEN
            RAISE EXCEPTION 'Override authorization approval requires the governed service';
        END IF;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status = 'APPROVED' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Approved assignment override authorizations are immutable';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER assignment_override_authorization_guard
BEFORE INSERT OR UPDATE OR DELETE
ON student_records_curriculumassignmentoverrideauthorization
FOR EACH ROW EXECUTE FUNCTION protect_assignment_override_authorization();
"""


def drop_legacy_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(DROP_LEGACY_GUARD_SQL)


def restore_legacy_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(RESTORE_LEGACY_GUARD_SQL)


def install_v2_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(V2_GUARD_SQL)


def remove_v2_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(DROP_LEGACY_GUARD_SQL)


def classify_legacy_override_authorizations(apps: object, schema_editor: object) -> None:
    del schema_editor
    authorization_model = apps.get_model(
        "student_records", "CurriculumAssignmentOverrideAuthorization"
    )  # type: ignore[attr-defined]
    decision_model = apps.get_model("student_records", "CurriculumAssignmentDecision")  # type: ignore[attr-defined]
    applied_ids = decision_model.objects.exclude(
        override_authorization_id__isnull=True
    ).values_list("override_authorization_id", flat=True)
    authorization_model.objects.filter(pk__in=applied_ids).update(seal_version="LEGACY_APPLIED")
    authorization_model.objects.exclude(pk__in=applied_ids).update(
        status="REJECTED",
        seal_version="LEGACY_UNCLASSIFIED",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0013_assignment_policy_guard_v2"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("student_records", "0017_assignment_override_authorization_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_legacy_guard, restore_legacy_guard),
        migrations.CreateModel(
            name="EnrollmentTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("ADMISSION", "Admission"),
                            ("REENTRY", "Reentry"),
                            ("TRANSFER", "Transfer"),
                            ("DUAL_DEGREE", "Dual Degree"),
                            ("PLAN_TRANSITION", "Plan Transition"),
                        ],
                        max_length=24,
                    ),
                ),
                ("decision_hash", models.CharField(max_length=64)),
                (
                    "source_previous_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("TRANSITIONED", "Transitioned"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source_result_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("TRANSITIONED", "Transitioned"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_term_id", models.UUIDField()),
                ("source_term_code", models.CharField(max_length=80)),
                ("source_term_starts_at", models.DateTimeField()),
                ("target_term_id", models.UUIDField()),
                ("target_term_code", models.CharField(max_length=80)),
                ("target_term_starts_at", models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="curriculumassignmentoverrideauthorization",
            name="assignment_override_approved_is_sealed",
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="revision_status",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="sealed_excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="sealed_locator",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="sealed_locator_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="sealed_source_title",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="curriculumassignmentoverrideauthorization",
            name="seal_version",
            field=models.CharField(
                choices=[
                    ("LEGACY_UNCLASSIFIED", "Legacy unclassified"),
                    ("LEGACY_APPLIED", "Legacy already applied"),
                    ("OVERRIDE_AUTH_V2", "Prepared evidence envelope v2"),
                ],
                default="LEGACY_UNCLASSIFIED",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("SUSPENDED", "Suspended"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("NEEDS_REVIEW", "Needs Review"),
                    ("TRANSITIONED", "Transitioned"),
                ],
                default="ACTIVE",
                max_length=24,
            ),
        ),
        migrations.RunPython(classify_legacy_override_authorizations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="curriculumassignmentoverrideauthorization",
            name="seal_version",
            field=models.CharField(
                choices=[
                    ("LEGACY_UNCLASSIFIED", "Legacy unclassified"),
                    ("LEGACY_APPLIED", "Legacy already applied"),
                    ("OVERRIDE_AUTH_V2", "Prepared evidence envelope v2"),
                ],
                default="OVERRIDE_AUTH_V2",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentoverrideauthorization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "APPROVED"), _negated=True),
                    ("seal_version", "LEGACY_APPLIED"),
                    models.Q(
                        ("approved_by__isnull", False),
                        ("approved_at__isnull", False),
                        models.Q(("content_hash", ""), _negated=True),
                        models.Q(("revision_content_hash", ""), _negated=True),
                        models.Q(("revision_source_set_hash", ""), _negated=True),
                        ("sealed_snapshot_id__isnull", False),
                        models.Q(("sealed_snapshot_sha256", ""), _negated=True),
                        models.Q(("sealed_storage_key_hash", ""), _negated=True),
                        models.Q(("sealed_excerpt_hash", ""), _negated=True),
                        models.Q(("sealed_locator_hash", ""), _negated=True),
                        models.Q(("sealed_locator", ""), _negated=True),
                        models.Q(("sealed_source_title", ""), _negated=True),
                        ("seal_version", "OVERRIDE_AUTH_V2"),
                        _connector="AND",
                    ),
                    _connector="OR",
                ),
                name="assignment_override_approved_is_sealed",
            ),
        ),
        migrations.RunPython(install_v2_guard, remove_v2_guard),
        migrations.AddField(
            model_name="enrollmenttransition",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_enrollment_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttransition",
            name="previous_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment_transitions_as_source_plan",
                to="curriculum.curriculumplan",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttransition",
            name="previous_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment_transitions_as_source_revision",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttransition",
            name="source_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_transitions",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddField(
            model_name="enrollmenttransition",
            name="target_enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transition",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmenttransition",
            index=models.Index(
                fields=["source_enrollment", "context"], name="enroll_transition_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmenttransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_enrollment", models.F("target_enrollment")), _negated=True
                ),
                name="enrollment_transition_distinct_rows",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmenttransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("context__in", ["REENTRY", "PLAN_TRANSITION"])),
                name="enrollment_transition_supported_context",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmenttransition",
            constraint=models.UniqueConstraint(
                fields=("source_enrollment", "context"),
                name="enrollment_transition_source_context_unique",
            ),
        ),
    ]
