# Generated by Django 6.0.8 on 2026-08-19 06:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LEDGER_GUARDS_SQL = """
CREATE OR REPLACE FUNCTION protect_verified_admission_fact()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE capability text;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') AND OLD.status = 'VERIFIED' THEN
        RAISE EXCEPTION 'Verified admission facts are immutable';
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') AND NEW.status = 'VERIFIED' THEN
        capability := current_setting('app.admission_fact_verification', true);
        IF capability IS DISTINCT FROM 'allowed' OR NEW.content_hash = ''
           OR NEW.sealed_snapshot_id IS NULL OR NEW.sealed_snapshot_sha256 = ''
           OR NEW.sealed_storage_key_hash = '' OR NEW.sealed_excerpt_hash = ''
           OR NEW.sealed_locator = '' OR NEW.sealed_source_title = ''
           OR NEW.sealed_provider = '' OR NEW.sealed_artifact_type = ''
           OR NEW.sealed_scope_hash = ''
           OR NEW.sealed_subject_identifier_hash = ''
           OR NEW.verified_by_id IS NULL OR NEW.verified_at IS NULL THEN
            RAISE EXCEPTION 'Admission facts can only be verified through governance';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS verified_admission_fact_guard
ON student_records_admissionfact;
CREATE TRIGGER verified_admission_fact_guard
BEFORE INSERT OR UPDATE OR DELETE ON student_records_admissionfact
FOR EACH ROW EXECUTE FUNCTION protect_verified_admission_fact();

CREATE OR REPLACE FUNCTION protect_enrollment_transition_ledger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    source_student uuid;
    target_student uuid;
    source_program uuid;
    target_program uuid;
    source_plan uuid;
    source_revision uuid;
    source_term uuid;
    target_term uuid;
    current_source_status varchar(24);
    source_code varchar(80);
    target_code varchar(80);
    source_start timestamptz;
    target_start timestamptz;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        RAISE EXCEPTION 'Enrollment transitions are append-only';
    END IF;
    SELECT student_id, program_id, plan_id, revision_basis_id, admission_term_id, status
      INTO source_student, source_program, source_plan, source_revision, source_term,
           current_source_status
      FROM student_records_programenrollment WHERE id = NEW.source_enrollment_id;
    SELECT student_id, program_id, admission_term_id
      INTO target_student, target_program, target_term
      FROM student_records_programenrollment WHERE id = NEW.target_enrollment_id;
    SELECT code, starts_at INTO source_code, source_start
      FROM offerings_academicterm WHERE id = source_term;
    SELECT code, starts_at INTO target_code, target_start
      FROM offerings_academicterm WHERE id = target_term;
    IF source_student IS DISTINCT FROM target_student
       OR source_program IS DISTINCT FROM target_program
       OR source_plan IS DISTINCT FROM NEW.previous_plan_id
       OR source_revision IS DISTINCT FROM NEW.previous_revision_id
       OR source_term IS DISTINCT FROM NEW.source_term_id
       OR target_term IS DISTINCT FROM NEW.target_term_id
       OR current_source_status IS DISTINCT FROM NEW.source_result_status
       OR source_code IS DISTINCT FROM NEW.source_term_code
       OR target_code IS DISTINCT FROM NEW.target_term_code
       OR source_start IS DISTINCT FROM NEW.source_term_starts_at
       OR target_start IS DISTINCT FROM NEW.target_term_starts_at
       OR target_start <= source_start THEN
        RAISE EXCEPTION 'Enrollment transition ledger scope or chronology is invalid';
    END IF;
    IF (NEW.context = 'PLAN_TRANSITION' AND (
            NEW.source_previous_status <> 'ACTIVE'
            OR NEW.source_result_status <> 'TRANSITIONED'
        )) OR (NEW.context = 'REENTRY' AND (
            NEW.source_previous_status NOT IN ('COMPLETED', 'SUSPENDED', 'WITHDRAWN', 'TRANSITIONED')
            OR NEW.source_result_status <> NEW.source_previous_status
        )) THEN
        RAISE EXCEPTION 'Enrollment transition lifecycle is invalid for its context';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS enrollment_transition_ledger_guard
ON student_records_enrollmenttransition;
CREATE TRIGGER enrollment_transition_ledger_guard
BEFORE INSERT OR UPDATE OR DELETE ON student_records_enrollmenttransition
FOR EACH ROW EXECUTE FUNCTION protect_enrollment_transition_ledger();

CREATE OR REPLACE FUNCTION protect_referenced_academic_term()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF (EXISTS (
        SELECT 1 FROM student_records_programenrollment
         WHERE admission_term_id = OLD.id
    ) OR EXISTS (
        SELECT 1 FROM student_records_admissionfact
         WHERE academic_term_id = OLD.id AND status = 'VERIFIED'
    )) AND (
        NEW.institution_id IS DISTINCT FROM OLD.institution_id
        OR NEW.campus_id IS DISTINCT FROM OLD.campus_id
        OR NEW.code IS DISTINCT FROM OLD.code
        OR NEW.starts_at IS DISTINCT FROM OLD.starts_at
        OR NEW.ends_at IS DISTINCT FROM OLD.ends_at
        OR NEW.source_snapshot_id IS DISTINCT FROM OLD.source_snapshot_id
    ) THEN
        RAISE EXCEPTION 'Referenced academic-term scope, dates and provenance are immutable';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS referenced_academic_term_guard ON offerings_academicterm;
CREATE TRIGGER referenced_academic_term_guard
BEFORE UPDATE ON offerings_academicterm
FOR EACH ROW EXECUTE FUNCTION protect_referenced_academic_term();
"""

REVERSE_GUARDS_SQL = """
DROP TRIGGER IF EXISTS referenced_academic_term_guard ON offerings_academicterm;
DROP FUNCTION IF EXISTS protect_referenced_academic_term();
DROP TRIGGER IF EXISTS enrollment_transition_ledger_guard
ON student_records_enrollmenttransition;
DROP FUNCTION IF EXISTS protect_enrollment_transition_ledger();
DROP TRIGGER IF EXISTS verified_admission_fact_guard
ON student_records_admissionfact;
DROP FUNCTION IF EXISTS protect_verified_admission_fact();
"""


def install_ledger_guards(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(LEDGER_GUARDS_SQL)


def remove_ledger_guards(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(REVERSE_GUARDS_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("institutions", "0001_initial"),
        ("offerings", "0004_split_scope_triggers"),
        ("student_records", "0020_normalize_historical_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_reference_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("DERIVED", "Derived"),
                            ("INFERRED_PENDING_REVIEW", "Inferred Pending Review"),
                            ("UNKNOWN", "Unknown"),
                            ("DISPUTED", "Disputed"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="UNKNOWN",
                        max_length=32,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("sealed_snapshot_id", models.UUIDField(blank=True, null=True)),
                ("sealed_snapshot_sha256", models.CharField(blank=True, max_length=64)),
                ("sealed_storage_key_hash", models.CharField(blank=True, max_length=64)),
                ("sealed_excerpt_hash", models.CharField(blank=True, max_length=64)),
                ("sealed_locator", models.CharField(blank=True, max_length=500)),
                ("sealed_source_title", models.CharField(blank=True, max_length=320)),
                ("sealed_provider", models.CharField(blank=True, max_length=160)),
                ("sealed_artifact_type", models.CharField(blank=True, max_length=80)),
                ("sealed_scope_hash", models.CharField(blank=True, max_length=64)),
                ("sealed_subject_identifier_hash", models.CharField(blank=True, max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_facts",
                        to="offerings.academicterm",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_facts",
                        to="governance.evidence",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_facts",
                        to="institutions.program",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verified_admission_facts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "academic_term", "record_reference_hash"),
                        name="admission_fact_program_term_reference_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "VERIFIED"), _negated=True),
                            models.Q(
                                models.Q(("content_hash", ""), _negated=True),
                                ("sealed_snapshot_id__isnull", False),
                                models.Q(("sealed_snapshot_sha256", ""), _negated=True),
                                models.Q(("sealed_storage_key_hash", ""), _negated=True),
                                models.Q(("sealed_excerpt_hash", ""), _negated=True),
                                models.Q(("sealed_locator", ""), _negated=True),
                                models.Q(("sealed_source_title", ""), _negated=True),
                                models.Q(("sealed_provider", ""), _negated=True),
                                models.Q(("sealed_artifact_type", ""), _negated=True),
                                models.Q(("sealed_scope_hash", ""), _negated=True),
                                models.Q(("sealed_subject_identifier_hash", ""), _negated=True),
                                ("verified_by__isnull", False),
                                ("verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="verified_admission_fact_is_sealed",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="curriculumassignmentdecision",
            name="admission_fact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_decision",
                to="student_records.admissionfact",
            ),
        ),
        migrations.RunPython(install_ledger_guards, remove_ledger_guards),
    ]
