# Generated by Django 6.0.8 on 2026-08-17 00:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(default="notification.requested", max_length=120)),
                ("dedupe_key", models.CharField(max_length=240, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUED", "Queued"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="QUEUED",
                        max_length=24,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "publication_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_requests",
                        to="governance.publicationevent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_outbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["available_at", "created_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "available_at"], name="notification_queue_idx"),
                    models.Index(
                        fields=["recipient", "created_at"], name="notification_recipient_idx"
                    ),
                    models.Index(
                        fields=["publication_event", "recipient"],
                        name="notif_event_recipient_idx",
                    ),
                ],
            },
        ),
    ]
