# Generated by Django 6.0.8 on 2026-08-17 01:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("IN_APP", "In App"), ("EMAIL", "Email")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="QUEUED",
                        max_length=24,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=240, unique=True)),
                ("locale", models.CharField(default="es-CO", max_length=16)),
                ("title_key", models.CharField(max_length=160)),
                ("body_key", models.CharField(max_length=160)),
                ("link_path", models.CharField(blank=True, max_length=240)),
                ("payload", models.JSONField(default=dict)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=240)),
                ("last_error_code", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_key", models.CharField(max_length=240, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("curriculum.revision.published", "Curriculum Revision Published")
                        ],
                        default="curriculum.revision.published",
                        max_length=120,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("message_key", models.CharField(max_length=160)),
                ("locale", models.CharField(default="es-CO", max_length=16)),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=120)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("locale", models.CharField(default="es-CO", max_length=16)),
            ],
            options={
                "ordering": ["event_type", "id"],
            },
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationoutbox",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationoutbox",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("SENDING", "Sending"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                    ("SUPPRESSED", "Suppressed"),
                ],
                default="QUEUED",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="notification_retry_queue_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="publication_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_event",
                to="governance.publicationevent",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="notifications.notificationevent",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["event_type", "published_at"], name="notification_event_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["publication_event", "published_at"], name="notification_event_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["recipient", "channel", "status", "created_at"],
                name="notification_delivery_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel", "status", "available_at"], name="notif_delivery_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("event", "recipient", "channel"), name="notification_delivery_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "event_type"], name="notif_pref_user_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "event_type"), name="notification_preference_unique"
            ),
        ),
    ]
