# Generated by Django 6.0.8 on 2026-08-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("curriculum", "0001_initial"),
        ("student_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditallocation",
            name="course_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_allocations",
                to="student_records.courseattempt",
            ),
        ),
        migrations.AddField(
            model_name="creditallocation",
            name="course_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_allocations",
                to="curriculum.courseversion",
            ),
        ),
        migrations.AddField(
            model_name="creditallocation",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_allocations",
                to="audit.degreeauditresult",
            ),
        ),
        migrations.AddField(
            model_name="degreeauditrun",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_runs",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddField(
            model_name="degreeauditrun",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_runs",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddField(
            model_name="degreeauditresult",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="result",
                to="audit.degreeauditrun",
            ),
        ),
        migrations.AddIndex(
            model_name="creditallocation",
            index=models.Index(
                fields=["result", "requirement_code"], name="allocation_result_requirement_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditallocation",
            index=models.Index(fields=["course_attempt"], name="allocation_attempt_idx"),
        ),
        migrations.AddConstraint(
            model_name="creditallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_credits__gte", 0)),
                name="credit_allocation_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="degreeauditrun",
            index=models.Index(
                fields=["enrollment", "-generated_at"], name="audit_run_enrollment_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="degreeauditrun",
            index=models.Index(
                fields=["revision", "engine_version"], name="audit_run_revision_engine_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="degreeauditrun",
            index=models.Index(fields=["result_hash"], name="audit_run_result_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="degreeauditresult",
            index=models.Index(
                fields=["status", "unknown_count"], name="audit_result_status_unknown_idx"
            ),
        ),
    ]
