# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("timezone", models.CharField(default="America/Bogota", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["institution__display_name", "code"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculties",
                        to="institutions.campus",
                    ),
                ),
            ],
            options={
                "ordering": ["campus__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("legal_name", models.CharField(max_length=240)),
                ("display_name", models.CharField(max_length=160)),
                ("country_code", models.CharField(default="CO", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
                "indexes": [
                    models.Index(fields=["status", "display_name"], name="inst_status_name_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="campus",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campuses",
                to="institutions.institution",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("snies", models.CharField(blank=True, max_length=40)),
                ("name", models.CharField(max_length=200)),
                ("degree_name", models.CharField(max_length=200)),
                ("estimated_terms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="institutions.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["faculty__name", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="faculty",
            index=models.Index(fields=["campus", "status"], name="faculty_campus_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="faculty",
            constraint=models.UniqueConstraint(
                fields=("campus", "code"), name="faculty_campus_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(fields=["institution", "status"], name="campus_inst_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="campus",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="campus_institution_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["faculty", "status"], name="program_faculty_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("faculty", "code"), name="program_faculty_code_unique"
            ),
        ),
    ]
