# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("active", models.BooleanField(default=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["institution__display_name", "code"],
            },
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=240)),
                ("credits", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course__code", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=240)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_plans",
                        to="institutions.program",
                    ),
                ),
            ],
            options={
                "ordering": ["program__name", "code"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_code", models.CharField(max_length=80)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("total_required_credits", models.PositiveIntegerField(default=0)),
                ("source_set_hash", models.CharField(blank=True, max_length=128)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="curriculum.curriculumplan",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.curriculumrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "revision_code"],
            },
        ),
        migrations.CreateModel(
            name="RequirementGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=240)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("COMPONENT", "Component"),
                            ("GROUP", "Group"),
                            ("GRADUATION", "Graduation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required_credits", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="curriculum.requirementgroup",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirement_groups",
                        to="curriculum.curriculumrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["revision", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PlanMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory"),
                            ("ELECTIVE_OPTION", "Elective Option"),
                            ("FREE_ELECTIVE_OPTION", "Free Elective Option"),
                            ("EXTERNAL_REFERENCE", "External Reference"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "count_policy",
                    models.CharField(
                        choices=[("COURSE", "Course"), ("CREDITS", "Credits"), ("ONCE", "Once")],
                        default="CREDITS",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "course_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_memberships",
                        to="curriculum.courseversion",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="curriculum.requirementgroup",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["institution", "active"], name="course_inst_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"), name="course_institution_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="courseversion",
            index=models.Index(
                fields=["course", "valid_from", "valid_to"], name="course_version_temporal_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.UniqueConstraint(
                fields=("course", "valid_from"), name="course_version_start_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="course_version_effective_range_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumplan",
            index=models.Index(fields=["program", "code"], name="plan_program_code_idx"),
        ),
        migrations.AddConstraint(
            model_name="curriculumplan",
            constraint=models.UniqueConstraint(
                fields=("program", "code"), name="plan_program_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="curriculumrevision",
            index=models.Index(fields=["plan", "status"], name="revision_plan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="curriculumrevision",
            index=models.Index(
                fields=["effective_from", "effective_to"], name="revision_effective_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumrevision",
            constraint=models.UniqueConstraint(
                fields=("plan", "revision_code"), name="revision_plan_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PUBLISHED")),
                fields=("plan",),
                name="revision_one_published_per_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="revision_effective_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_required_credits__gte", 0)),
                name="revision_credits_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="requirementgroup",
            index=models.Index(fields=["revision", "kind"], name="req_group_revision_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="requirementgroup",
            index=models.Index(fields=["parent", "sort_order"], name="req_group_parent_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="requirementgroup",
            constraint=models.UniqueConstraint(
                fields=("revision", "code"), name="requirement_group_revision_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="requirementgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("required_credits__gte", 0)),
                name="requirement_group_credits_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="planmembership",
            index=models.Index(fields=["revision", "role"], name="membership_revision_role_idx"),
        ),
        migrations.AddIndex(
            model_name="planmembership",
            index=models.Index(
                fields=["group", "course_version"], name="membership_group_course_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planmembership",
            constraint=models.UniqueConstraint(
                fields=("revision", "course_version", "group"),
                name="membership_revision_course_group_unique",
            ),
        ),
    ]
