# Generated by Django 6.0.8 on 2026-08-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0002_published_revision_immutability"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumrevision",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
