# Generated by Django 6.0.8 on 2026-08-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0011_curriculumassignmentpolicy_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculumassignmentpolicy",
            name="allow_retired_revision",
            field=models.BooleanField(default=False),
        ),
    ]
