# Generated by Django 6.0.8 on 2026-08-19 06:19

from django.db import migrations, models

DROP_PUBLISHED_EVIDENCE_GUARD_SQL = """
DROP TRIGGER IF EXISTS protect_curriculum_assignment_policy_evidence_trigger
ON curriculum_curriculumassignmentpolicyevidence;
DROP FUNCTION IF EXISTS protect_curriculum_assignment_policy_evidence();
"""

RESTORE_PUBLISHED_EVIDENCE_GUARD_SQL = """
CREATE OR REPLACE FUNCTION protect_curriculum_assignment_policy_evidence()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE policy_status varchar(24);
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        SELECT status INTO policy_status FROM curriculum_curriculumassignmentpolicy WHERE id = OLD.policy_id;
        IF policy_status IN ('PUBLISHED', 'SUPERSEDED', 'RETIRED') THEN
            RAISE EXCEPTION 'Evidence cannot be removed from a published curriculum assignment policy';
        END IF;
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        SELECT status INTO policy_status FROM curriculum_curriculumassignmentpolicy WHERE id = NEW.policy_id;
        IF policy_status IN ('PUBLISHED', 'SUPERSEDED', 'RETIRED') THEN
            RAISE EXCEPTION 'Evidence cannot be added to a published curriculum assignment policy';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER protect_curriculum_assignment_policy_evidence_trigger
BEFORE INSERT OR UPDATE OR DELETE ON curriculum_curriculumassignmentpolicyevidence
FOR EACH ROW EXECUTE FUNCTION protect_curriculum_assignment_policy_evidence();
"""


def drop_published_evidence_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(DROP_PUBLISHED_EVIDENCE_GUARD_SQL)


def restore_published_evidence_guard(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(RESTORE_PUBLISHED_EVIDENCE_GUARD_SQL)


def normalize_pre_review_material(apps: object, schema_editor: object) -> None:
    del schema_editor
    policy_model = apps.get_model("curriculum", "CurriculumAssignmentPolicy")  # type: ignore[attr-defined]
    link_model = apps.get_model("curriculum", "CurriculumAssignmentPolicyEvidence")  # type: ignore[attr-defined]
    allowed = {
        "LEGACY_UNCLASSIFIED",
        "NORMATIVE_PUBLICATION",
        "ASSIGNMENT_SCOPE",
        "TARGET_REVISION",
        "CONTEXT_RULE",
        "ASSIGNMENT_OVERRIDE_AUTHORITY",
    }
    invalid = link_model.objects.exclude(purpose__in=allowed)
    invalid.update(purpose="LEGACY_UNCLASSIFIED")
    policy_model.objects.filter(status="IN_REVIEW").update(
        status="DRAFT",
        source_set_hash="",
        content_hash="",
    )


def degrade_review_material_before_reverse(apps: object, schema_editor: object) -> None:
    del schema_editor
    policy_model = apps.get_model("curriculum", "CurriculumAssignmentPolicy")  # type: ignore[attr-defined]
    policy_model.objects.filter(status="IN_REVIEW").update(
        status="DRAFT",
        source_set_hash="",
        content_hash="",
    )


REVIEW_GUARD_SQL = """
CREATE OR REPLACE FUNCTION protect_reviewed_assignment_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    review_capability text;
    publication_capability text;
    sealed_evidence_count integer;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'Assignment policies must be created as draft';
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'DELETE' THEN
        IF OLD.status = 'IN_REVIEW' THEN
            RAISE EXCEPTION 'Assignment policies under review cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'DRAFT' AND NEW.status = 'IN_REVIEW' THEN
        review_capability := current_setting('app.assignment_policy_review_submission', true);
        SELECT count(*) INTO sealed_evidence_count
          FROM curriculum_curriculumassignmentpolicyevidence
         WHERE policy_id = NEW.id
           AND sealed_snapshot_sha256 <> ''
           AND sealed_snapshot_id IS NOT NULL
           AND sealed_storage_key_hash <> ''
           AND sealed_excerpt_hash <> ''
           AND sealed_locator_hash <> ''
           AND sealed_excerpt <> ''
           AND sealed_locator <> ''
           AND sealed_source_title <> '';
        IF review_capability IS DISTINCT FROM 'allowed'
           OR NEW.content_hash = '' OR NEW.source_set_hash = ''
           OR sealed_evidence_count < 1 THEN
            RAISE EXCEPTION 'Assignment policy review submission is not governed or sealed';
        END IF;
    END IF;
    IF OLD.status = 'IN_REVIEW' THEN
        publication_capability := current_setting('app.assignment_policy_publication', true);
        IF NEW.status NOT IN ('IN_REVIEW', 'PUBLISHED')
           OR (NEW.status = 'PUBLISHED' AND publication_capability IS DISTINCT FROM 'allowed')
           OR NEW.policy_code IS DISTINCT FROM OLD.policy_code
           OR NEW.version IS DISTINCT FROM OLD.version
           OR NEW.program_id IS DISTINCT FROM OLD.program_id
           OR NEW.plan_id IS DISTINCT FROM OLD.plan_id
           OR NEW.revision_basis_id IS DISTINCT FROM OLD.revision_basis_id
           OR NEW.context IS DISTINCT FROM OLD.context
           OR NEW.admission_from IS DISTINCT FROM OLD.admission_from
           OR NEW.admission_to IS DISTINCT FROM OLD.admission_to
           OR NEW.cohort_code IS DISTINCT FROM OLD.cohort_code
           OR NEW.previous_plan_id IS DISTINCT FROM OLD.previous_plan_id
           OR NEW.normative_published_on IS DISTINCT FROM OLD.normative_published_on
           OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
           OR NEW.effective_to IS DISTINCT FROM OLD.effective_to
           OR NEW.allow_retired_revision IS DISTINCT FROM OLD.allow_retired_revision
           OR NEW.epistemic_status IS DISTINCT FROM OLD.epistemic_status
           OR NEW.source_set_hash IS DISTINCT FROM OLD.source_set_hash
           OR NEW.supersedes_id IS DISTINCT FROM OLD.supersedes_id
           OR NEW.metadata IS DISTINCT FROM OLD.metadata
           OR NEW.prepared_by_id IS DISTINCT FROM OLD.prepared_by_id THEN
            RAISE EXCEPTION 'Assignment policy content under review is immutable';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reviewed_assignment_policy_guard
ON curriculum_curriculumassignmentpolicy;
CREATE TRIGGER reviewed_assignment_policy_guard
BEFORE INSERT OR UPDATE OR DELETE ON curriculum_curriculumassignmentpolicy
FOR EACH ROW EXECUTE FUNCTION protect_reviewed_assignment_policy();

CREATE OR REPLACE FUNCTION protect_reviewed_assignment_policy_evidence()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    old_status varchar(24);
    new_status varchar(24);
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        SELECT status INTO old_status FROM curriculum_curriculumassignmentpolicy
         WHERE id = OLD.policy_id;
        IF old_status = 'IN_REVIEW' THEN
            RAISE EXCEPTION 'Evidence under assignment-policy review is immutable';
        END IF;
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        SELECT status INTO new_status FROM curriculum_curriculumassignmentpolicy
         WHERE id = NEW.policy_id;
        IF new_status = 'IN_REVIEW' THEN
            RAISE EXCEPTION 'Evidence cannot be added to an assignment policy under review';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reviewed_assignment_policy_evidence_guard
ON curriculum_curriculumassignmentpolicyevidence;
CREATE TRIGGER reviewed_assignment_policy_evidence_guard
BEFORE INSERT OR UPDATE OR DELETE ON curriculum_curriculumassignmentpolicyevidence
FOR EACH ROW EXECUTE FUNCTION protect_reviewed_assignment_policy_evidence();
"""

REVERSE_GUARD_SQL = """
DROP TRIGGER IF EXISTS reviewed_assignment_policy_evidence_guard
ON curriculum_curriculumassignmentpolicyevidence;
DROP FUNCTION IF EXISTS protect_reviewed_assignment_policy_evidence();
DROP TRIGGER IF EXISTS reviewed_assignment_policy_guard
ON curriculum_curriculumassignmentpolicy;
DROP FUNCTION IF EXISTS protect_reviewed_assignment_policy();
"""


def install_review_guards(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(REVIEW_GUARD_SQL)


def remove_review_guards(apps: object, schema_editor: object) -> None:
    del apps
    if schema_editor.connection.vendor == "postgresql":  # type: ignore[attr-defined]
        with schema_editor.connection.cursor() as cursor:  # type: ignore[attr-defined]
            cursor.execute(REVERSE_GUARD_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0013_assignment_policy_guard_v2"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
    ]

    operations = [
        migrations.RunPython(
            drop_published_evidence_guard,
            restore_published_evidence_guard,
        ),
        migrations.AddField(
            model_name="curriculumassignmentpolicyevidence",
            name="sealed_excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="curriculumassignmentpolicyevidence",
            name="sealed_locator",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="curriculumassignmentpolicyevidence",
            name="sealed_source_title",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name="curriculumassignmentpolicyevidence",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("LEGACY_UNCLASSIFIED", "Legacy unclassified"),
                    ("NORMATIVE_PUBLICATION", "Normative publication"),
                    ("ASSIGNMENT_SCOPE", "Assignment scope"),
                    ("TARGET_REVISION", "Target revision"),
                    ("CONTEXT_RULE", "Context rule"),
                    ("ASSIGNMENT_OVERRIDE_AUTHORITY", "Assignment override authority"),
                ],
                default="LEGACY_UNCLASSIFIED",
                max_length=120,
            ),
        ),
        migrations.RunPython(
            normalize_pre_review_material,
            degrade_review_material_before_reverse,
        ),
        migrations.AddConstraint(
            model_name="curriculumassignmentpolicyevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    purpose__in=[
                        "LEGACY_UNCLASSIFIED",
                        "NORMATIVE_PUBLICATION",
                        "ASSIGNMENT_SCOPE",
                        "TARGET_REVISION",
                        "CONTEXT_RULE",
                        "ASSIGNMENT_OVERRIDE_AUTHORITY",
                    ]
                ),
                name="assignment_policy_evidence_purpose_valid",
            ),
        ),
        migrations.RunPython(
            restore_published_evidence_guard,
            drop_published_evidence_guard,
        ),
        migrations.RunPython(install_review_guards, remove_review_guards),
    ]
