# Generated by Django 6.0.8 on 2026-08-21 18:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0014_curriculumassignmentpolicyevidence_sealed_excerpt_and_more"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        ("rules", "0004_published_requirement_immutability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("layout_code", models.CharField(max_length=80)),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("SOURCE_FAITHFUL_LAYOUT", "Source Faithful Layout"),
                            ("DEPENDENCY_DERIVED_LAYOUT", "Dependency Derived Layout"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "viewport",
                    models.CharField(
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("TABLET", "Tablet"),
                            ("MOBILE", "Mobile"),
                        ],
                        default="DESKTOP",
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(default="es-CO", max_length=20)),
                ("title", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                (
                    "epistemic_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("DERIVED", "Derived"),
                            ("INFERRED_PENDING_REVIEW", "Inferred Pending Review"),
                            ("UNKNOWN", "Unknown"),
                            ("DISPUTED", "Disputed"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="UNKNOWN",
                        max_length=32,
                    ),
                ),
                ("source_evidence_reference", models.TextField(blank=True)),
                ("source_set_hash", models.CharField(blank=True, max_length=128)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_normative", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("layout_version", models.PositiveIntegerField(default=1)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_curriculum_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_curriculum_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layouts",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_layouts",
                        to="governance.sourcesnapshot",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="curriculum.curriculumlayout",
                    ),
                ),
            ],
            options={
                "ordering": ["revision__plan__program_id", "revision_id", "layout_code"],
            },
        ),
        migrations.CreateModel(
            name="LayoutNodeOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("node_code", models.CharField(max_length=120)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("COURSE", "Course"),
                            ("CHOICE_POOL", "Choice Pool"),
                            ("FREE_ELECTIVE_POOL", "Free Elective Pool"),
                            ("EXTERNAL_REQUIREMENT", "External Requirement"),
                            ("MILESTONE", "Milestone"),
                            ("ANNOTATION", "Annotation"),
                        ],
                        max_length=36,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=240)),
                ("source_column", models.CharField(blank=True, max_length=80)),
                ("source_lane", models.CharField(blank=True, max_length=80)),
                (
                    "source_row",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                (
                    "source_col",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("source_rowspan", models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ("source_colspan", models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ("slot_count", models.PositiveIntegerField(blank=True, null=True)),
                ("required_credits", models.PositiveIntegerField(blank=True, null=True)),
                ("progression_count", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="curriculum.curriculumlayout",
                    ),
                ),
                (
                    "target_course_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_occurrences",
                        to="curriculum.courseversion",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_occurrences",
                        to="curriculum.requirementgroup",
                    ),
                ),
                (
                    "target_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layout_occurrences",
                        to="rules.requirement",
                    ),
                ),
            ],
            options={
                "ordering": ["layout_id", "display_order", "node_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.UniqueConstraint(
                fields=("revision", "layout_code"), name="curriculum_layout_revision_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("layout_type__in", ["SOURCE_FAITHFUL_LAYOUT", "DEPENDENCY_DERIVED_LAYOUT"])
                ),
                name="curriculum_layout_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "IN_REVIEW", "PUBLISHED", "SUPERSEDED", "RETIRED"])
                ),
                name="curriculum_layout_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "epistemic_status__in",
                        [
                            "VERIFIED",
                            "DERIVED",
                            "INFERRED_PENDING_REVIEW",
                            "UNKNOWN",
                            "DISPUTED",
                            "SUPERSEDED",
                        ],
                    )
                ),
                name="curriculum_layout_epistemic_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("layout_code", ""), _negated=True),
                name="curriculum_layout_layout_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("layout_version__gte", 1)),
                name="curriculum_layout_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="curriculum_layout_effective_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["SUPERSEDED", "RETIRED"]), ("supersedes_id__isnull", False)
                    ),
                    models.Q(("status__in", ["SUPERSEDED", "RETIRED"]), _negated=True),
                    _connector="OR",
                ),
                name="curriculum_layout_superseded_needs_predecessor",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.UniqueConstraint(
                fields=("layout", "node_code"), name="layout_node_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("node_code", ""), _negated=True),
                name="layout_node_code_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "node_type__in",
                        [
                            "COURSE",
                            "CHOICE_POOL",
                            "FREE_ELECTIVE_POOL",
                            "EXTERNAL_REQUIREMENT",
                            "MILESTONE",
                            "ANNOTATION",
                        ],
                    )
                ),
                name="layout_node_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)),
                name="layout_node_display_order_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("slot_count__isnull", True), ("slot_count__gte", 0), _connector="OR"
                ),
                name="layout_node_slot_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="layoutnodeoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("node_type", "COURSE"),
                        ("target_course_version_id__isnull", False),
                        ("target_group_id__isnull", True),
                        ("target_requirement_id__isnull", True),
                    ),
                    models.Q(
                        ("node_type__in", ["CHOICE_POOL", "FREE_ELECTIVE_POOL", "MILESTONE"]),
                        ("target_course_version_id__isnull", True),
                        ("target_group_id__isnull", False),
                        ("target_requirement_id__isnull", True),
                    ),
                    models.Q(
                        ("node_type", "EXTERNAL_REQUIREMENT"),
                        ("target_course_version_id__isnull", True),
                        ("target_group_id__isnull", True),
                        ("target_requirement_id__isnull", False),
                    ),
                    models.Q(
                        ("node_type", "ANNOTATION"),
                        ("target_course_version_id__isnull", True),
                        ("target_group_id__isnull", True),
                        ("target_requirement_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="layout_node_single_typed_target",
            ),
        ),
    ]
