# Generated by Django 6.0.8 on 2026-08-21 18:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0015_curriculumlayout_layoutnodeoccurrence_and_more"),
        ("governance", "0004_publicationevent_publicationimpact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="curriculumlayout",
            name="curriculum_layout_revision_code_unique",
        ),
        migrations.AddConstraint(
            model_name="curriculumlayout",
            constraint=models.UniqueConstraint(
                fields=("revision", "layout_code", "layout_version"),
                name="curriculum_layout_revision_code_version_unique",
            ),
        ),
    ]
