# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_hash", models.CharField(max_length=128)),
                ("solver_version", models.CharField(max_length=80)),
                ("status", models.CharField(max_length=24)),
                ("objective_values", models.JSONField(default=dict)),
                ("solution", models.JSONField(default=dict)),
                ("explanation", models.JSONField(default=dict)),
                ("time_limit_seconds", models.PositiveIntegerField(default=60)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
