# Generated by Django 6.0.8 on 2026-08-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("optimization", "0001_initial"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationrun",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="optimization_runs",
                to="planning.planscenario",
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(
                fields=["scenario", "status"], name="optimization_scenario_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optimizationrun",
            index=models.Index(fields=["input_hash"], name="optimization_input_hash_idx"),
        ),
    ]
