# Generated by Django 6.0.8 on 2026-08-16 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="optimizationrun",
            new_name="opt_scenario_status_idx",
            old_name="optimization_scenario_status_idx",
        ),
    ]
