# Generated by Django 6.0.8 on 2026-08-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offerings", "0001_initial"),
        ("planning", "0001_initial"),
        ("student_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planscenario",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_scenarios",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddField(
            model_name="planscenario",
            name="target_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_scenarios",
                to="offerings.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="planningpreference",
            name="scenario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planning_preferences",
                to="planning.planscenario",
            ),
        ),
        migrations.AddField(
            model_name="plannedcourse",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_courses",
                to="planning.planscenario",
            ),
        ),
        migrations.AddIndex(
            model_name="planscenario",
            index=models.Index(
                fields=["enrollment", "status"], name="scenario_enrollment_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planscenario",
            index=models.Index(fields=["target_term"], name="scenario_target_term_idx"),
        ),
        migrations.AddConstraint(
            model_name="planscenario",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "name"), name="scenario_enrollment_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="planscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="scenario_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_credits_per_term__gte", models.F("min_credits_per_term"))),
                name="planning_credit_limits_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="plannedcourse",
            index=models.Index(
                fields=["scenario", "term", "priority"], name="planned_course_scenario_term_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedcourse",
            index=models.Index(
                fields=["course_version", "term"], name="planned_course_course_term_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcourse",
            constraint=models.UniqueConstraint(
                fields=("scenario", "course_version", "term"),
                name="planned_course_scenario_term_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedcourse",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 0)), name="planned_course_priority_nonnegative"
            ),
        ),
    ]
