# Generated by Django 6.0.8 on 2026-08-16 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plannedcourse",
            new_name="planned_scenario_term_idx",
            old_name="planned_course_scenario_term_idx",
        ),
    ]
