# Generated by Django 6.0.8 on 2026-08-16 17:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offerings", "0002_source_freshness_and_meeting_dates"),
        ("planning", "0003_rename_planned_course_scenario_term_idx_planned_scenario_term_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedcourse",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plannedcourse",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_courses",
                to="offerings.section",
            ),
        ),
        migrations.AddField(
            model_name="planscenario",
            name="share_token",
            field=models.UUIDField(
                blank=True, default=None, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="planscenario",
            name="sharing_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ScenarioAuditProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_fingerprint", models.CharField(max_length=128)),
                ("revision_hash", models.CharField(blank=True, max_length=128)),
                ("engine_version", models.CharField(max_length=80)),
                ("result_hash", models.CharField(max_length=128)),
                ("generated_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("unknown_count", models.PositiveIntegerField(default=0)),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_projection",
                        to="planning.planscenario",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["result_hash"], name="scenario_projection_hash_idx"),
                    models.Index(fields=["generated_at"], name="scenario_projection_time_idx"),
                ],
            },
        ),
    ]
