# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_kind", models.CharField(max_length=80)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("storage_key", models.CharField(blank=True, max_length=500)),
                ("parser_version", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("VALIDATING", "Validating"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
