# Generated by Django 6.0.8 on 2026-08-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("imports", "0001_initial"),
        ("student_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="student_records.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["student", "status"], name="import_student_status_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["content_sha256"], name="import_content_hash_idx"),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_sha256", ""), _negated=True),
                fields=("student", "content_sha256"),
                name="import_student_hash_unique",
            ),
        ),
    ]
