# Generated by Django 6.0.8 on 2026-08-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_curriculumrevision_metadata"),
        ("governance", "0002_changeproposal"),
        ("imports", "0002_initial"),
        (
            "student_records",
            "0002_rename_exception_enrollment_status_idx_exception_enroll_status_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="content_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="curriculum_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="report_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="schema_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="semantic_diff",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="source_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="governance.sourcesnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("content_fingerprint__gt", ""), ("source_kind", "CURRICULUM_BASELINE")
                ),
                fields=("source_kind", "content_fingerprint", "parser_version"),
                name="curriculum_import_fingerprint_unique",
            ),
        ),
    ]
