# Generated by Django 6.0.8 on 2026-08-16 08:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_published_revision_metadata_immutability"),
        ("governance", "0002_changeproposal"),
        ("imports", "0003_importbatch_content_fingerprint_and_more"),
        ("offerings", "0001_initial"),
        ("student_records", "0004_courseattempt_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("source_locator", models.CharField(max_length=240)),
                ("candidate_fingerprint", models.CharField(max_length=64)),
                ("raw_payload", models.JSONField(default=dict)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("parse_errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("requires_confirmation", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid"),
                            ("CONFLICT", "Conflict"),
                            ("ERROR", "Error"),
                            ("RESOLVED", "Resolved"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("conflict_details", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="ImportEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_locator", models.CharField(max_length=240)),
                ("excerpt", models.TextField(blank=True)),
                ("excerpt_hash", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="RawArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("mime_type", models.CharField(max_length=120)),
                ("storage_key", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("STORED", "Stored"), ("REJECTED", "Rejected")],
                        default="STORED",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPT", "Accept"),
                            ("EXTERNAL", "External"),
                            ("SKIP", "Skip"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("external_code", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="importbatch",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="confirmed_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="history_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received"),
                    ("VALIDATING", "Validating"),
                    ("PREVIEW", "Preview"),
                    ("VALIDATED", "Validated"),
                    ("REJECTED", "Rejected"),
                    ("APPLIED", "Applied"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["created_by", "created_at"], name="import_creator_time_idx"),
        ),
        migrations.AddField(
            model_name="candidaterecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_records",
                to="imports.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="candidaterecord",
            name="suggested_course_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggested_import_candidates",
                to="curriculum.courseversion",
            ),
        ),
        migrations.AddField(
            model_name="candidaterecord",
            name="suggested_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suggested_import_candidates",
                to="offerings.academicterm",
            ),
        ),
        migrations.AddField(
            model_name="importevidence",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence",
                to="imports.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importevidence",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence",
                to="imports.candidaterecord",
            ),
        ),
        migrations.AddField(
            model_name="importevidence",
            name="course_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_evidence",
                to="student_records.courseattempt",
            ),
        ),
        migrations.AddField(
            model_name="rawartifact",
            name="batch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifact",
                to="imports.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="rawartifact",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_import_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importevidence",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence",
                to="imports.rawartifact",
            ),
        ),
        migrations.AddField(
            model_name="reconciliation",
            name="candidate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation",
                to="imports.candidaterecord",
            ),
        ),
        migrations.AddField(
            model_name="reconciliation",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_reconciliations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliation",
            name="selected_course_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="selected_import_reconciliations",
                to="curriculum.courseversion",
            ),
        ),
        migrations.AddIndex(
            model_name="candidaterecord",
            index=models.Index(fields=["batch", "status"], name="candidate_batch_status_idx"),
        ),
        migrations.AddIndex(
            model_name="candidaterecord",
            index=models.Index(
                fields=["batch", "candidate_fingerprint"], name="candidate_batch_fp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterecord",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="candidate_batch_row_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__lte", 100)), name="candidate_confidence_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="rawartifact",
            index=models.Index(fields=["content_sha256"], name="artifact_content_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="rawartifact",
            index=models.Index(fields=["status", "created_at"], name="artifact_status_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="artifact_size_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="importevidence",
            index=models.Index(fields=["course_attempt"], name="import_evidence_attempt_idx"),
        ),
        migrations.AddIndex(
            model_name="importevidence",
            index=models.Index(
                fields=["artifact", "source_locator"], name="import_evidence_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importevidence",
            constraint=models.UniqueConstraint(
                fields=("candidate", "source_locator"),
                name="import_evidence_candidate_locator_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="reconciliation",
            index=models.Index(fields=["decision", "decided_at"], name="recon_decision_time_idx"),
        ),
    ]
