# Generated by Django 6.0.8 on 2026-08-16 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_published_revision_metadata_immutability"),
        ("governance", "0002_changeproposal"),
        ("imports", "0004_candidaterecord_importevidence_rawartifact_and_more"),
        ("student_records", "0004_courseattempt_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="student_records.programenrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["enrollment", "status"], name="import_enroll_status_idx"),
        ),
    ]
