# Generated by Django 6.0.8 on 2026-08-16 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_published_revision_metadata_immutability"),
        ("governance", "0002_changeproposal"),
        ("imports", "0005_importbatch_enrollment_and_more"),
        ("student_records", "0004_courseattempt_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="importbatch",
            name="import_student_hash_unique",
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("enrollment__isnull", False), models.Q(("content_sha256", ""), _negated=True)
                ),
                fields=("enrollment", "content_sha256"),
                name="import_enrollment_hash_unique",
            ),
        ),
    ]
