# Generated by Django 6.0.8 on 2026-08-16 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0004_published_revision_metadata_immutability"),
        ("governance", "0002_changeproposal"),
        ("imports", "0006_remove_importbatch_import_student_hash_unique_and_more"),
        ("student_records", "0004_courseattempt_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["enrollment", "idempotency_key"], name="import_enrollment_key_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("enrollment__isnull", False), models.Q(("idempotency_key", ""), _negated=True)
                ),
                fields=("enrollment", "idempotency_key"),
                name="import_enrollment_idempotency_unique",
            ),
        ),
    ]
