# Generated by Django 6.0.8 on 2026-08-17 21:44

import modules.imports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_importbatch_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterecord',
            name='raw_payload_expires_at',
            field=models.DateTimeField(default=modules.imports.models.history_raw_payload_expiry),
        ),
        migrations.AddField(
            model_name='candidaterecord',
            name='raw_payload_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
