# Generated by Django 6.0.8 on 2026-08-18 01:20

from django.conf import settings
from django.db import migrations, models

import modules.imports.models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0009_candidaterecord_candidate_raw_retention_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rawartifact",
            name="content_expires_at",
            field=models.DateTimeField(default=modules.imports.models.history_raw_payload_expiry),
        ),
        migrations.AddField(
            model_name="rawartifact",
            name="content_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawartifact",
            name="status",
            field=models.CharField(
                choices=[("STORED", "Stored"), ("REJECTED", "Rejected"), ("PURGED", "Purged")],
                default="STORED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rawartifact",
            name="storage_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="rawartifact",
            index=models.Index(
                fields=["content_purged_at", "content_expires_at"], name="artifact_retention_idx"
            ),
        ),
    ]
