# Generated by Django 6.0.8 on 2026-08-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0010_rawartifact_content_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawartifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("STORED", "Stored"),
                    ("REJECTED", "Rejected"),
                    ("PURGE_PENDING", "Purge Pending"),
                    ("PURGED", "Purged"),
                ],
                default="STORED",
                max_length=20,
            ),
        ),
    ]
