# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_type", models.CharField(max_length=80)),
                ("owner_id", models.UUIDField()),
                ("code", models.CharField(max_length=120)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ENROLLMENT_PREREQUISITE", "Enrollment Prerequisite"),
                            ("COREQUISITE", "Corequisite"),
                            ("GROUP_COMPLETION", "Group Completion"),
                            ("GRADUATION", "Graduation"),
                            ("PRACTICE_ELIGIBILITY", "Practice Eligibility"),
                            ("SUBSTITUTION", "Substitution"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ast", models.JSONField(default=dict)),
                ("ast_hash", models.CharField(blank=True, max_length=64)),
                (
                    "epistemic_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("DERIVED", "Derived"),
                            ("INFERRED_PENDING_REVIEW", "Inferred Pending Review"),
                            ("UNKNOWN", "Unknown"),
                            ("DISPUTED", "Disputed"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="UNKNOWN",
                        max_length=32,
                    ),
                ),
                ("explanation_key", models.CharField(blank=True, max_length=240)),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True, related_name="requirements", to="governance.evidence"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["owner_type", "owner_id"], name="requirement_owner_idx"),
                    models.Index(
                        fields=["purpose", "epistemic_status"],
                        name="requirement_purpose_status_idx",
                    ),
                    models.Index(fields=["ast_hash"], name="requirement_ast_hash_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_type", "owner_id", "code"),
                        name="requirement_owner_code_unique",
                    )
                ],
            },
        ),
    ]
