# Generated by Django 6.0.8 on 2026-08-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_curriculumrevision_metadata"),
        ("governance", "0002_changeproposal"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="requirement",
            name="requirement_owner_code_unique",
        ),
        migrations.AddField(
            model_name="requirement",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="requirement",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requirements",
                to="curriculum.curriculumrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.UniqueConstraint(
                fields=("revision", "owner_type", "owner_id", "code"),
                name="requirement_revision_owner_code_unique",
            ),
        ),
    ]
