# Generated by Django 6.0.8 on 2026-08-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0002_remove_requirement_requirement_owner_code_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="ast_schema_version",
            field=models.CharField(default="1.0.0", max_length=32),
        ),
    ]
