# Generated by Django 6.0.8 on 2026-08-16 05:48

from django.db import migrations

import modules.identity.models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", modules.identity.models.UserManager()),
            ],
        ),
    ]
