# Generated by Django 6.0.8 on 2026-08-16 07:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION protect_identity_audit_event() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Audit events are append-only';
END;
$$;
DROP TRIGGER IF EXISTS protect_identity_audit_event_trigger ON identity_auditevent;
CREATE TRIGGER protect_identity_audit_event_trigger
    BEFORE UPDATE OR DELETE ON identity_auditevent
    FOR EACH ROW EXECUTE FUNCTION protect_identity_audit_event();
"""

REVERSE_SQL = """
DROP TRIGGER IF EXISTS protect_identity_audit_event_trigger ON identity_auditevent;
DROP FUNCTION IF EXISTS protect_identity_audit_event();
"""


def install_audit_event_trigger(apps: object, schema_editor: object) -> None:
    del apps
    connection = schema_editor.connection  # type: ignore[attr-defined]
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(TRIGGER_SQL)


def remove_audit_event_trigger(apps: object, schema_editor: object) -> None:
    del apps
    connection = schema_editor.connection  # type: ignore[attr-defined]
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(REVERSE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_alter_user_managers"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_hash", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=80)),
                ("window_started_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "window_started_at"], name="rate_limit_action_window_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key_hash", "action", "window_started_at"),
                        name="rate_limit_bucket_identity_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=120)),
                ("object_type", models.CharField(blank=True, max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                ("request_id", models.CharField(blank=True, max_length=80)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["action", "created_at"], name="audit_event_action_idx"),
                    models.Index(fields=["actor", "created_at"], name="audit_event_actor_idx"),
                    models.Index(
                        fields=["object_type", "object_id"], name="audit_event_object_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("ADVISOR", "Advisor"),
                            ("EDITOR", "Editor"),
                            ("REVIEWER", "Reviewer"),
                            ("ANALYST", "Analyst"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="institutions.institution",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="institutions.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "role", "active"], name="role_user_active_idx"),
                    models.Index(fields=["institution", "role"], name="role_institution_idx"),
                    models.Index(fields=["program", "role"], name="role_program_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__isnull", True),
                            ("valid_from__isnull", True),
                            ("valid_to__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="role_assignment_valid_range",
                    )
                ],
            },
        ),
        migrations.RunPython(install_audit_event_trigger, remove_audit_event_trigger),
    ]
