# Generated by Django 6.0.8 on 2026-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0007_role_assignment_scope_invariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initial_password_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
