# Generated by Django 6.0.8 on 2026-08-19 03:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0008_user_initial_password_expires_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("middle_names", models.CharField(blank=True, max_length=160)),
                ("first_surname", models.CharField(blank=True, max_length=80)),
                ("second_surname", models.CharField(blank=True, max_length=80)),
                ("preferred_name", models.CharField(blank=True, max_length=160)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "birth_date_purpose",
                    models.CharField(
                        blank=True,
                        choices=[("ACADEMIC_ADMINISTRATION", "Academic administration")],
                        max_length=48,
                    ),
                ),
                ("birth_date_retention_until", models.DateField(blank=True, null=True)),
                (
                    "data_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("LEGACY_UNSTRUCTURED", "Legacy unstructured"),
                            ("NEEDS_REVIEW", "Needs review"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=32,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_surname", "second_surname", "first_name", "user__email"],
                "indexes": [
                    models.Index(
                        fields=["first_surname", "first_name"], name="person_surname_name_idx"
                    ),
                    models.Index(fields=["data_status"], name="person_data_status_idx"),
                ],
            },
        ),
    ]
