# Generated by Django 6.0.8 on 2026-08-19 03:32

from django.db import migrations, models


def classify_existing_confirmed_profiles(apps, schema_editor):  # type: ignore[no-untyped-def]
    PersonProfile = apps.get_model("identity", "PersonProfile")
    AuditEvent = apps.get_model("identity", "AuditEvent")
    for profile in PersonProfile.objects.filter(data_status="CONFIRMED").iterator():
        latest_event = (
            AuditEvent.objects.filter(
                object_type="PersonProfile",
                object_id=str(profile.pk),
                action__in=(
                    "PERSON_IDENTITY_RECTIFIED",
                    "PERSON_IDENTITY_SELF_RECTIFIED",
                ),
            )
            .order_by("-created_at", "-id")
            .first()
        )
        profile.verification_method = (
            "INSTITUTION_VERIFIED"
            if latest_event and latest_event.action == "PERSON_IDENTITY_RECTIFIED"
            else "SELF_DECLARED"
            if latest_event and latest_event.action == "PERSON_IDENTITY_SELF_RECTIFIED"
            else "PREEXISTING_UNCLASSIFIED"
        )
        if profile.confirmed_at is None:
            profile.confirmed_at = profile.created_at
        profile.save(update_fields=["verification_method", "confirmed_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0009_personprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="personprofile",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("LEGACY_UNKNOWN", "Legacy or unknown"),
                    ("PREEXISTING_UNCLASSIFIED", "Preexisting unclassified"),
                    ("SELF_DECLARED", "Self declared"),
                    ("INSTITUTION_VERIFIED", "Institution verified"),
                ],
                default="LEGACY_UNKNOWN",
                max_length=32,
            ),
        ),
        migrations.RunPython(classify_existing_confirmed_profiles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="personprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("data_status", "CONFIRMED"), _negated=True),
                    models.Q(
                        models.Q(("first_name", ""), _negated=True),
                        models.Q(("first_surname", ""), _negated=True),
                        ("confirmed_at__isnull", False),
                        models.Q(("verification_method", "LEGACY_UNKNOWN"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="person_confirmed_identity_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="personprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("birth_date__isnull", True),
                        ("birth_date_purpose", ""),
                        ("birth_date_retention_until__isnull", True),
                    ),
                    models.Q(
                        ("birth_date__isnull", False),
                        models.Q(("birth_date_purpose", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="person_birth_date_has_purpose",
            ),
        ),
    ]
