# Generated by Django 6.0.8 on 2026-08-16 05:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NormativeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issuer", models.CharField(max_length=240)),
                ("document_type", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=320)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUPERSEDED", "Superseded"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-year", "document_type", "number"],
                "indexes": [
                    models.Index(fields=["document_type", "year"], name="normative_type_year_idx"),
                    models.Index(
                        fields=["status", "publication_date"], name="normative_status_date_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "document_type", "number", "year"),
                        name="normative_document_identity_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("year__gte", 1900)),
                        name="normative_document_year_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField()),
                ("sha256", models.CharField(max_length=64)),
                ("mime_type", models.CharField(max_length=120)),
                ("storage_key", models.CharField(max_length=500)),
                ("source_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="governance.normativedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, max_length=240)),
                ("line_locator", models.CharField(blank=True, max_length=240)),
                ("excerpt_hash", models.CharField(max_length=128)),
                ("excerpt", models.TextField(blank=True)),
                ("annotation", models.TextField(blank=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="governance.sourcesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("AMENDS", "Amends"),
                            ("REPEALS", "Repeals"),
                            ("ADDS", "Adds"),
                            ("CLARIFIES", "Clarifies"),
                            ("SUPERSEDES", "Supersedes"),
                        ],
                        max_length=24,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_relations",
                        to="governance.normativedocument",
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relations",
                        to="governance.normativedocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_document", "relation"], name="norm_relation_source_idx"
                    ),
                    models.Index(
                        fields=["target_document", "relation"], name="norm_relation_target_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_document", "target_document", "relation"),
                        name="norm_relation_identity_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_document", models.F("target_document")), _negated=True
                        ),
                        name="norm_relation_not_self",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sourcesnapshot",
            index=models.Index(
                fields=["document", "-captured_at"], name="snapshot_document_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcesnapshot",
            index=models.Index(fields=["sha256"], name="snapshot_sha256_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcesnapshot",
            constraint=models.UniqueConstraint(
                fields=("document", "sha256"), name="snapshot_document_hash_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("sha256__regex", "^[0-9a-fA-F]{64}$")),
                name="snapshot_sha256_hex",
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["snapshot", "page"], name="evidence_snapshot_page_idx"),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(fields=["excerpt_hash"], name="evidence_excerpt_hash_idx"),
        ),
    ]
