# Generated by Django 6.0.8 on 2026-08-16 06:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0003_curriculumrevision_metadata"),
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proposal_key", models.CharField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=320)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("content_fingerprint", models.CharField(max_length=64)),
                ("semantic_diff", models.JSONField(default=dict)),
                ("rationale", models.TextField(blank=True)),
                (
                    "base_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_proposals_as_base",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "candidate_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_proposals_as_candidate",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_change_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_proposals",
                        to="governance.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["candidate_revision", "status"],
                        name="proposal_candidate_status_idx",
                    ),
                    models.Index(fields=["content_fingerprint"], name="proposal_fingerprint_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate_revision", "content_fingerprint"),
                        name="proposal_candidate_fingerprint_unique",
                    )
                ],
            },
        ),
    ]
