# Generated by Django 6.0.8 on 2026-08-17 00:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_rename_allocation_result_requirement_idx_alloc_result_req_idx_and_more"),
        ("curriculum", "0004_published_revision_metadata_immutability"),
        ("governance", "0003_extractioncandidate_publication_review"),
        ("student_records", "0004_courseattempt_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_key", models.CharField(max_length=180, unique=True)),
                (
                    "event_type",
                    models.CharField(default="curriculum.revision.published", max_length=120),
                ),
                ("schema_version", models.CharField(default="1.0", max_length=24)),
                ("changed_courses", models.JSONField(blank=True, default=list)),
                ("changed_groups", models.JSONField(blank=True, default=list)),
                ("changed_requirements", models.JSONField(blank=True, default=list)),
                ("impact_summary", models.JSONField(blank=True, default=dict)),
                ("recompute_plan", models.JSONField(blank=True, default=dict)),
                ("notification_plan", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_publication_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_event",
                        to="governance.publication",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_events",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "superseded_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_publication_events",
                        to="curriculum.curriculumrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicationImpact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_audit_result_hash", models.CharField(blank=True, max_length=128)),
                ("changed_courses", models.JSONField(blank=True, default=list)),
                ("changed_groups", models.JSONField(blank=True, default=list)),
                ("changed_requirements", models.JSONField(blank=True, default=list)),
                (
                    "impact_status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("RECOMPUTE_QUEUED", "Recompute Queued"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("RECOMPUTED", "Recomputed"),
                        ],
                        default="RECOMPUTE_QUEUED",
                        max_length=32,
                    ),
                ),
                ("recompute_job_key", models.CharField(max_length=240, unique=True)),
                ("recompute_requested_at", models.DateTimeField()),
                ("requires_revision_decision", models.BooleanField(default=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_publication_impacts",
                        to="student_records.programenrollment",
                    ),
                ),
                (
                    "previous_audit_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_impacts",
                        to="audit.degreeauditrun",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_impacts_as_previous",
                        to="curriculum.curriculumrevision",
                    ),
                ),
                (
                    "publication_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_impacts",
                        to="governance.publicationevent",
                    ),
                ),
                (
                    "recomputed_audit_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recomputed_publication_impacts",
                        to="audit.degreeauditrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="publicationevent",
            index=models.Index(
                fields=["revision", "created_at"], name="pub_event_revision_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationevent",
            index=models.Index(
                fields=["superseded_revision", "created_at"], name="pub_event_superseded_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationimpact",
            index=models.Index(
                fields=["publication_event", "impact_status"], name="pub_impact_event_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationimpact",
            index=models.Index(
                fields=["enrollment", "impact_status"], name="pub_impact_enroll_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationimpact",
            constraint=models.UniqueConstraint(
                fields=("publication_event", "enrollment"),
                name="publication_event_enrollment_unique",
            ),
        ),
    ]
